### PR TITLE
STORM-3959 - Add Matomo Tracking

### PR DESCRIPTION
**Pull request by rzo1**
as the title says

### CODE REVIEW

**Comment by rzo1** [comment]
Actual change is in `_includes/footer.html`. The rest is re-generated content.

**Comment by avermeer** [comment]
Sorry I missed this review request. By the way, as far as I understand Matomo will help measuring the audience of Storm's site, right?

If that's so, then where the stats will be visible ?

**Comment by rzo1** [comment]
https://matomo.privacy.apache.org/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=38#?period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1 :)

**Comment by avermeer** [comment]
Nice, will that be linked from Storm-site ?

**Comment by rzo1** [comment]
We can do that, if we want it to be available to everyone. There is (afaik) no ASF policy which prevents it.

**Pull request merged**
